### numpy

In [52]:
import numpy as np

In [53]:
np.array([2,4,6,7])

array([2, 4, 6, 7])

In [54]:
arr = np.array([i for i in range(1,10)], dtype=np.int32)
# arr = np.array(list(range(1,10)), dtype=np.int32)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr.shape

(9,)

In [56]:
arr.reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr = arr.reshape((3,3))

In [59]:
a = np.ones([2,2])
b = np.ones([2,2])
a

array([[1., 1.],
       [1., 1.]])

In [60]:
a+b

array([[2., 2.],
       [2., 2.]])

In [61]:
a==b

array([[ True,  True],
       [ True,  True]])

In [62]:
a is b

False

In [63]:
a = np.arange(3,9)
c = np.array([True, True, False, True, True, True])
print(a)
print(a[c])

[3 4 5 6 7 8]
[3 4 6 7 8]


In [64]:
c*1

array([1, 1, 0, 1, 1, 1])

مطالعه بیشتر
* np.random.shuffle
* np.arange
* np.zeros
* np.ones
* np.concatenate
* arr.shape
* np.random.randn
* np.array vs matrix
* np.exp
* np.sqrt
* arr.argmax
* np.random.seed
* np.linspace
* ndarrays vs matrices