# Numpy

In [2]:
import numpy as np

In [53]:
np.array([2,4,6,7])

array([2, 4, 6, 7])

In [54]:
arr = np.array([i for i in range(1,10)], dtype=np.int32)
# arr = np.array(list(range(1,10)), dtype=np.int32)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr.shape

(9,)

In [56]:
arr.reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr = arr.reshape((3,3))

In [10]:
print(np.zeros([3,3]))
print(np.ones([3,3]))
print(np.full((3,3), 10))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [28]:
a = np.ones([2,2])
b = np.ones([2,2])
a

array([[1., 1.],
       [1., 1.]])

In [23]:
a+b

array([[2., 2.],
       [2., 2.]])

In [31]:
a==b

array([[ True,  True],
       [ True,  True]])

In [32]:
a is b

False

In [33]:
b=b*4
np.vstack([b,a])

array([[4., 4.],
       [4., 4.],
       [1., 1.],
       [1., 1.]])

In [34]:
np.hstack([a,b])

array([[1., 1., 4., 4.],
       [1., 1., 4., 4.]])

In [55]:
a = np.arange(1,6)
b = np.arange(2,-3,-1)
print(a)
print(b)

[1 2 3 4 5]
[ 2  1  0 -1 -2]


In [56]:
a+b

array([3, 3, 3, 3, 3])

In [57]:
a-b

array([-1,  1,  3,  5,  7])

In [58]:
a*b

array([  2,   2,   0,  -4, -10])

In [61]:
c = np.arange(0,5)
print(c)
a**c

[0 1 2 3 4]


array([  1,   2,   9,  64, 625], dtype=int32)

In [62]:
np.dot(a,b)

-10

In [43]:
a/b

d:\apps\python3.7.5\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ 0.5,  2. ,  inf, -4. , -2.5])

In [51]:
np.float64(1.0)/0.0
# ارور نداد

d:\apps\python3.7.5\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in double_scalars
  """Entry point for launching an IPython kernel.


inf

In [52]:
np.float64(0.0)/0.0

d:\apps\python3.7.5\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in double_scalars
  """Entry point for launching an IPython kernel.


nan

In [54]:
# 1.0/0.0 
# ارور میده

In [63]:
a = np.arange(3,9)
c = np.array([True, True, False, True, True, True])
print(a)
print(a[c])

[3 4 5 6 7 8]
[3 4 6 7 8]


In [64]:
c*1

array([1, 1, 0, 1, 1, 1])

In [6]:
arr1 = np.array([1,2,3,4]*4)
print(arr1)
arr2 = np.repeat([1,2,3,4],4)
print(arr2)

[1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4]
[1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4]


## ضرب ماتریسی و برداری
* matmul
* dot
* multiply

In [77]:
a = np.arange(1,10).reshape(3,3)
b = np.array([[3,4,5],
              [6,2,1],
              [5,2,3]])
print('a:')
print(a)
print('\nb:')
print(b)

a:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

b:
[[3 4 5]
 [6 2 1]
 [5 2 3]]


In [78]:
print('\ndot:')
print(np.dot(a,b))
print('\nmultiply:')
print(np.multiply(a,b))
print('\nmatmul:')
print(np.matmul(a,b))
print('\nusing @:')
print(a@b)


dot:
[[ 30  14  16]
 [ 72  38  43]
 [114  62  70]]

multiply:
[[ 3  8 15]
 [24 10  6]
 [35 16 27]]

matmul:
[[ 30  14  16]
 [ 72  38  43]
 [114  62  70]]

using @:
[[ 30  14  16]
 [ 72  38  43]
 [114  62  70]]


## transpose یا ترانهاد


<!--![](Transpose1.png)-->

<img src="./Transpose1.png" width="500"/>

In [69]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

مطالعه بیشتر
* np.random.shuffle
* np.arange
* np.zeros
* np.ones
* np.concatenate
* arr.shape
* np.random.randn
* np.array vs matrix
* np.exp
* np.sqrt
* arr.argmax
* np.random.seed
* np.linspace
* ndarrays vs matrices