## markdown cell
.میتونید اینجا هرچیزی بنویسید و نمایشی هست فقط. برای توضیحات در کل خیلی خوبه چون در کنار خوندن یک چیزی مثل مستند کد هم میتونید اجرا کنید

# heading 1
## heading 2
### heading 3
...

## latex
میتونید لتک بنویسید همینجا با علامت 

$

مثال:

$$
\frac{\sqrt{x^2-1}}{e^x} 
$$

In [1]:
print('hello world')

hello world


میتونید مثل ماشین حساب مستقیم نتایج محاسبات رو چک کنید به این صورت:

In [2]:
9+4

13

In [3]:
9-4

5

In [4]:
9*4

36

In [5]:
9/4

2.25

فرق // با / اینه که // خارج قسمت یا جز صحیح حاصل تقسیم رو میده اما / دقیق با اعشار حساب میکنه

In [6]:
9//4

2

In [7]:
9%4

1

به توان رسوندن:

In [8]:
9**4

6561

کارای جالبی که میشه روی رشته ها انجام داد:

In [9]:
print('بالای خط:')
print('-'*5, end=",")
print('روی','خط', sep=' ')
print('زیر خط')
print('worldd'[0:-1])

بالای خط:
-----,روی خط
زیر خط
world


تو پایتون لازم نیست نوع متغیرها رو بنویسید.

همچنین نوع متغیرها میتونه در طول برنامه کامل تغییر کنه و مشکلی نداره.

در مورد interpreterها و نحوه عملکردشون اگه خواستید مطالعه کنید.

In [10]:
a = 1
print(type(a))
a = 'Robotics!'
print(type(a))
a = 1.0
print(type(a))

<class 'int'>
<class 'str'>
<class 'float'>


In [11]:
print(a)

1.0


In [12]:
myinput = input("گرفتن ورودی: ")

گرفتن ورودی: 256


In [13]:
type(myinput)

str

یه فرق دیگه پایتون با جاوا:
نمیتونید عدد رو به یه رشته اضافه کنید.

In [14]:
1+'256'

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [15]:
myinput+str(1)

'2561'

### بولین یا boolean

In [16]:
a = True
b = False
type(a)

bool

In [17]:
a and b

False

In [18]:
a or b

True

In [19]:
a is b

False

In [20]:
a == b

False

In [21]:
a != b

True

In [22]:
not b

True

در مورد علامت == و is:
    
عملگر == فقط مقدار دو متغیر رو چک میکنه

عملگر is نه تنها چک میکنه مقدار دوتا یکی باشه بلکه چک میکنه رفرنس یا شی هر دو عملوند یکی باشه
مثال:


In [23]:
list1 = [1, 2, 3]
list2 = [1, 2, 3]
print(list1 == list2)
print(list1 is list2)

True
False


بر خلاف جاواسکریپت:

In [24]:
a = 'True'
b = True
a == b

False

آرایه یا همون لیست

In [25]:
arr = [1,2,3,4,5,6]
arr2d = [[1,2],[1,2,3],[4]]
arr2d

[[1, 2], [1, 2, 3], [4]]

In [26]:
arr.append('last')
arr

[1, 2, 3, 4, 5, 6, 'last']

In [27]:
arr[-1]

'last'

In [28]:
arr[-2]

6

In [29]:
# slicing
arr[1:-1]

[2, 3, 4, 5, 6]

In [30]:
arr[1:-1]+arr[0:1]

[2, 3, 4, 5, 6, 1]

In [31]:
arr[1:2]*5

[2, 2, 2, 2, 2]

### اجراهای شرطی:

In [32]:
a = True
if a:
    print(1)
if not a:
    print('why, it shouldn\'t print')
elif not 1:
    print('shouldn\'t run')
else:
    print('should run')

1
should run


### حلقه ها:

In [33]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [34]:
cnt=1
while(cnt < 10):
    print(cnt)
    cnt += 1

1
2
3
4
5
6
7
8
9


کار جالب و خوانایی که با ساختن لیست ها تو پایتون میشه انجام داد:

In [35]:
[i for i in range(1,10) if i%2==0]

[2, 4, 6, 8]

In [36]:
list(range(0,5))

[0, 1, 2, 3, 4]

### توابع

In [37]:
def function1(a):
    print (a)
    a = 2
    print(a)
    return -1

In [38]:
b = 3
result = function1(b)
print(b)

3
2
3


In [39]:
def function2(a, *parameters):
    print(a)
    print(parameters)
    return +1

معادل کد بالا تو جاوا:

#### java equivaent:
``` java
private static int function2(int a, int ... myparams){
    System.out.println(a);
    System.out.println(myparams);
    return 1;
}
```

In [40]:
function2(1,2,4,5,6)
# میتونید هر چقد میخواید پارامتر بنویسید اینطوری
function2(1,2,3,4,5,6,7,7);

1
(2, 4, 5, 6)
1
(2, 3, 4, 5, 6, 7, 7)


In [41]:
def function3(a, *parameters, b):
    print(a)
    print(b)
    print(parameters)

In [42]:
function3(1,2,4,5,6,7)

TypeError: function3() missing 1 required keyword-only argument: 'b'

In [43]:
function3(1,2,2,3,b=7)

1
7
(2, 2, 3)


پارامتر اختیاری:

In [44]:
def function4(a=1, b=3):
    print(a)
    print(b)
    return a+b

In [45]:
function4()

1
3


4

In [46]:
function4(10)

10
3


13

In [47]:
function4(b=2, a=6)

6
2


8

In [48]:
def callfunction(myfunction,b,a):
    print(myfunction(b,a))
    
callfunction(function4, b=2, a=6)

2
6
8


In [49]:
add = function4
add(2,6)

2
6


8

In [50]:
type(add)

function

انواع متغیرهایی که تا به اینجا دیدیم:
پرسش کلاسی: میتونید حدس بزنید نوع متغیرها رو؟ بعضی از اینها رو اصلا در موردشون صحبت نکردیم و نمیکنیم.

In [51]:
# numeric types
a = 1
a = 1.5

a = 2j
# sequence types:
a = ['sbu', 'robotics', 'summer']
a = ('sbu', 'robotics', 'summer')
a = range(10)

# mapping types:
a = {"fname":"Ali", "lname":"Alavi"}

# set types:
a = {'sbu', 'robotics', 'summer'}

a = ({'sbu', 'robotics', 'summer'}) # frozenset

# boolean types:
a = True

# text type:
a = 'sbu cse robotics'

# binary types:
a = b'sbu' # bytes
a = bytearray(5) # bytearray
print('bytearray:', a)
a = memoryview(bytes(5)) # memoryview
print('memoryview:', a)
# None types:
a = None


bytearray: bytearray(b'\x00\x00\x00\x00\x00')
memoryview: <memory at 0x00000176CEB7F648>


## کتابخانه های پایتون:

### numpy

In [52]:
import numpy as np

In [53]:
np.array([2,4,6,7])

array([2, 4, 6, 7])

In [54]:
arr = np.array([i for i in range(1,10)], dtype=np.int32)
# arr = np.array(list(range(1,10)), dtype=np.int32)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr.shape

(9,)

In [56]:
arr.reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr = arr.reshape((3,3))

In [59]:
a = np.ones([2,2])
b = np.ones([2,2])
a

array([[1., 1.],
       [1., 1.]])

In [60]:
a+b

array([[2., 2.],
       [2., 2.]])

In [61]:
a==b

array([[ True,  True],
       [ True,  True]])

In [62]:
a is b

False

In [63]:
a = np.arange(3,9)
c = np.array([True, True, False, True, True, True])
print(a)
print(a[c])

[3 4 5 6 7 8]
[3 4 6 7 8]


In [64]:
c*1

array([1, 1, 0, 1, 1, 1])

مطالعه بیشتر
* np.random.shuffle
* np.arange
* np.zeros
* np.ones
* np.concatenate
* arr.shape
* np.random.randn
* np.array vs matrix
* np.exp
* np.sqrt
* arr.argmax
* np.random.seed
* np.linspace
* ndarrays vs matrices

### pandas

In [65]:
import pandas as pd

In [66]:
labels = ['a', 'b', 'c']
my_list = [1, 2, 3]
arr = np.array(my_list)
d = {'a':10, 'b':20, 'c':30}

In [67]:
pd.Series(data=my_list)

0    1
1    2
2    3
dtype: int64

In [68]:
pd.Series(my_list, labels)

a    1
b    2
c    3
dtype: int64

In [69]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [70]:
np.random.seed(1)
df = pd.DataFrame(np.random.randn(5,4), index = 'A B C D E'.split(), columns='W X Y Z'.split())

In [71]:
df.head(3)

W         X         Y         Z
A  1.624345 -0.611756 -0.528172 -1.072969
B  0.865408 -2.301539  1.744812 -0.761207
C  0.319039 -0.249370  1.462108 -2.060141

In [72]:
df

W         X         Y         Z
A  1.624345 -0.611756 -0.528172 -1.072969
B  0.865408 -2.301539  1.744812 -0.761207
C  0.319039 -0.249370  1.462108 -2.060141
D -0.322417 -0.384054  1.133769 -1.099891
E -0.172428 -0.877858  0.042214  0.582815

In [73]:
df['W']

A    1.624345
B    0.865408
C    0.319039
D   -0.322417
E   -0.172428
Name: W, dtype: float64

In [74]:
df[['W', 'Z']]

W         Z
A  1.624345 -1.072969
B  0.865408 -0.761207
C  0.319039 -2.060141
D -0.322417 -1.099891
E -0.172428  0.582815

In [75]:
df.W

A    1.624345
B    0.865408
C    0.319039
D   -0.322417
E   -0.172428
Name: W, dtype: float64

In [76]:
df['new'] = df['W']+df.Y

In [77]:
df

W         X         Y         Z       new
A  1.624345 -0.611756 -0.528172 -1.072969  1.096174
B  0.865408 -2.301539  1.744812 -0.761207  2.610219
C  0.319039 -0.249370  1.462108 -2.060141  1.781147
D -0.322417 -0.384054  1.133769 -1.099891  0.811352
E -0.172428 -0.877858  0.042214  0.582815 -0.130214

In [78]:
df.drop('new', axis=+1)

W         X         Y         Z
A  1.624345 -0.611756 -0.528172 -1.072969
B  0.865408 -2.301539  1.744812 -0.761207
C  0.319039 -0.249370  1.462108 -2.060141
D -0.322417 -0.384054  1.133769 -1.099891
E -0.172428 -0.877858  0.042214  0.582815

In [79]:
df

W         X         Y         Z       new
A  1.624345 -0.611756 -0.528172 -1.072969  1.096174
B  0.865408 -2.301539  1.744812 -0.761207  2.610219
C  0.319039 -0.249370  1.462108 -2.060141  1.781147
D -0.322417 -0.384054  1.133769 -1.099891  0.811352
E -0.172428 -0.877858  0.042214  0.582815 -0.130214

In [90]:
df.loc[['A','C']].add(df.loc[['B','D']], fill_value=0)

W         X         Y         Z       new
A  1.624345 -0.611756 -0.528172 -1.072969  1.096174
B  0.865408 -2.301539  1.744812 -0.761207  2.610219
C  0.319039 -0.249370  1.462108 -2.060141  1.781147
D -0.322417 -0.384054  1.133769 -1.099891  0.811352

In [85]:
df

W         X         Y         Z       new
A  1.624345 -0.611756 -0.528172 -1.072969  1.096174
B  0.865408 -2.301539  1.744812 -0.761207  2.610219
C  0.319039 -0.249370  1.462108 -2.060141  1.781147
D -0.322417 -0.384054  1.133769 -1.099891  0.811352
E -0.172428 -0.877858  0.042214  0.582815 -0.130214