## markdown cell
.میتونید اینجا هرچیزی بنویسید و نمایشی هست فقط. برای توضیحات در کل خیلی خوبه چون در کنار خوندن یک چیزی مثل مستند کد هم میتونید اجرا کنید

# heading 1
## heading 2
### heading 3
...

## latex
میتونید لتک بنویسید همینجا با علامت 

$

مثال:

$$
\frac{\sqrt{x^2-1}}{e^x} 
$$

In [3]:
print('hello world')

hello world


میتونید مثل ماشین حساب مستقیم نتایج محاسبات رو چک کنید به این صورت:

In [1]:
9+4

13

In [2]:
9-4

5

In [3]:
9*4

36

In [4]:
9/4

2.25

فرق // با / اینه که // خارج قسمت یا جز صحیح حاصل تقسیم رو میده اما / دقیق با اعشار حساب میکنه

In [5]:
9//4

2

In [7]:
9%4

1

به توان رسوندن:

In [8]:
9**4

6561

کارای جالبی که میشه روی رشته ها انجام داد:

In [12]:
print('بالای خط:')
print('-'*5, end=",")
print('روی','خط', sep=' ')
print('زیر خط')
print('worldd'[0:-1])

بالای خط:
-----,روی خط
زیر خط
world


تو پایتون لازم نیست نوع متغیرها رو بنویسید.

همچنین نوع متغیرها میتونه در طول برنامه کامل تغییر کنه و مشکلی نداره.

در مورد interpreterها و نحوه عملکردشون اگه خواستید مطالعه کنید.

In [13]:
a = 1
a = 'Robotics!'
a = 1.0

In [14]:
print(a)

1.0


In [16]:
myinput = input("گرفتن ورودی: ")

گرفتن ورودی: 256


In [17]:
type(myinput)

str

یه فرق دیگه پایتون با جاوا:
نمیتونید عدد رو به یه رشته اضافه کنید.

In [18]:
1+'256'

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [20]:
myinput+str(1)

'2561'

### بولین یا boolean

In [22]:
a = True
b = False

In [23]:
a and b

False

In [24]:
a or b

True

In [25]:
a is b

False

In [26]:
a == b

False

In [27]:
a != b

True

In [38]:
not b

True

در مورد علامت == و is:
    
عملگر == فقط مقدار دو متغیر رو چک میکنه

عملگر is نه تنها چک میکنه مقدار دوتا یکی باشه بلکه چک میکنه رفرنس یا شی هر دو عملوند یکی باشه
مثال:


In [40]:
list1 = [1, 2, 3]
list2 = [1, 2, 3]
print(list1 == list2)
print(list1 is list2)

True
False


بر خلاف جاواسکریپت:

In [41]:
a = 'True'
b = True
a == b

False

آرایه یا همون لیست

In [10]:
arr = [1,2,3,4,5,6]
arr2d = [[1,2],[1,2,3],[4]]
arr2d

[[1, 2], [1, 2, 3], [4]]

In [51]:
arr.append('last')
arr

[1, 2, 3, 4, 5, 6, 'last']

In [54]:
arr[-1]

'last'

In [55]:
arr[-2]

6

In [56]:
# slicing
arr[1:-1]

[2, 3, 4, 5, 6]

In [57]:
arr[1:-1]+arr[0:1]

[2, 3, 4, 5, 6, 1]

In [58]:
arr[1:2]*5

[2, 2, 2, 2, 2]

### اجراهای شرطی:

In [1]:
a = True
if a:
    print(1)
if not a:
    print('why, it shouldn\'t print')
elif not 1:
    print('shouldn\'t run')
else:
    print('should run')

1
should run


### حلقه ها:

In [2]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [4]:
cnt=1
while(cnt < 10):
    print(cnt)
    cnt += 1

1
2
3
4
5
6
7
8
9


کار جالب و خوانایی که با ساختن لیست ها تو پایتون میشه انجام داد:

In [5]:
[i for i in range(1,10) if i%2==0]

[2, 4, 6, 8]

In [7]:
list(range(0,5))

[0, 1, 2, 3, 4]

### توابع

In [11]:
def function1(a):
    print (a)
    a = 2
    print(a)
    return -1

In [12]:
b = 3
result = function1(b)
print(b)

3
2
3


In [24]:
def function2(a, *parameters):
    print(a)
    print(parameters)
    return +1

معادل کد بالا تو جاوا:

#### java equivaent:
``` java
private static int function2(int a, int ... myparams){
    System.out.println(a);
    System.out.println(myparams);
    return 1;
}
```

In [25]:
function2(1,2,4,5,6)
# میتونید هر چقد میخواید پارامتر بنویسید اینطوری
functionSecond(1,2,3,4,5,6,7,7);

1
(2, 4, 5, 6)
1
(2, 3, 4, 5, 6, 7, 7)


In [26]:
def function3(a, *parameters, b):
    print(a)
    print(b)
    print(parameters)

In [27]:
function3(1,2,4,5,6,7)

TypeError: function3() missing 1 required keyword-only argument: 'b'

In [28]:
function3(1,2,2,3,b=7)

1
7
(2, 2, 3)


پارامتر اختیاری:

In [29]:
def function4(a=1, b=3):
    print(a)
    print(b)
    return a+b

In [30]:
function4()

1
3


4

In [31]:
function4(10)

10
3


13

In [33]:
function4(b=2, a=6)

6
2


8

## کتابخانه های پایتون:

### numpy

In [4]:
import numpy as np

In [13]:
arr = np.array([i for i in range(1,10)], dtype=np.int32)
# arr = np.array(list(range(1,10)), dtype=np.int32)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr.shape

(9,)

In [15]:
arr.reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr = arr.reshape((3,3))

In [30]:
a = np.ones([2,2])
b = np.ones([2,2])
a

array([[1., 1.],
       [1., 1.]])

In [20]:
a+b

array([[2., 2.],
       [2., 2.]])

In [21]:
a==b

array([[ True,  True],
       [ True,  True]])

In [22]:
a is b

False

In [28]:
a = np.arange(3,9)
c = np.array([True, True, False, True, True, True])
print(a)
print(a[c])

[3 4 5 6 7 8]
[3 4 6 7 8]


In [29]:
c*1

array([1, 1, 0, 1, 1, 1])

In [ ]:
مطالعه بیشتر
* 

### pandas

In [1]:
import pandas as pd

10